### PR TITLE
Added CocoaPods support

### PR DESCRIPTION
**Pull request by avishic**
Added a .podspec file to allow using VectorBoolean with cocoapods.

### CODE REVIEW

**Comment by avishic** [comment]
After merging CocoaPods support, please add a tag '0.1.0' for it to work properly

**Comment by lrtitze** [comment]
Thanks for your patience as well as the time you expended, @avishic 

I finally had the time to get back to this to merge your contribution.

**Comment by lrtitze** [comment]
I haven't yet added the tag. Just noticed the comment you left but I'm in iOctocat on my phone.

**Comment by lrtitze** [comment]
CocoaPods should have version 0.2.0 soon. I seem to have worked out most of the kinks.

**Pull request merged**
