### PR TITLE
Upgrade to Swift 3.0

### PR DESCRIPTION
**Pull request by LouisDhauwe**
This pull request upgrades the whole project, including unit tests, to Swift 3.0.
The majority of the conversion was done by the Swift migrator in Xcode.
In my quick test runs, everything seems to work and behave as before.

I've also added some @discardableResult annotations where I felt confident that they were appropriate.

Please note that currently there are 6 failures when running the unit tests. These are not new in this Swift 3.0 upgrade, these are present in the current, Swift 2.2, version.

### CODE REVIEW

**Comment by LouisDhauwe** [comment]
@lrtitze Can you take a look please?

**Comment by lrtitze** [comment]
Looking now. Sorry about the delay, I was mired in other work.

**Comment by lrtitze** [comment]
@LouisDhauwe It all looks good! Thanks so much for your hard work!

**Comment by lrtitze** [comment]
Merged and credited. Good work.  :-)

**Pull request merged**
