### PR TITLE
Add framework target

### PR DESCRIPTION
**Pull request by an0**

### CODE REVIEW

**Comment by lrtitze** [comment]
This looks good as well. I'll be checking it soon and will probably merge it in later in the day.

Again, thank you for contributing.

**Comment by an0** [comment]
I haven’t yet refactored the 2 existing targets to use the framework. One reason is I don’t have much experience with test targets. So I suggest you do that after the merge.

Thanks for your work.

**Comment by lrtitze** [comment]
Should I be setting a value for VectorBooleanVersionNumber and VectorBooleanVersionString somewhere in the source?

**Comment by an0** [comment]
I don’t think so.

**Comment by lrtitze** [comment]
Okay, I think I found the related docs for framework version numbers.

I'll look at refactoring the demo app to use the framework. It won't happen today though as I'm pushing up against deadlines in my regular project.

I'm actually considering removing most of the test code as it was actually debug code that I just shoved in there to simplify simple test cases while I was doing the original conversion from OS X to iOS. A library like this is extremely difficult to write proper tests for.

**Comment by lrtitze** [comment]
Sorry to bother you with this but the Swift 3 work is in there now. I ran into problems trying to merge your last pull request but would be willing to give it another go if you can get it working with this one.

**Comment by an0** [comment]
I'll take a look after I update my apps to Swift 3.

**Comment by an0** [comment]
Sorry for the delay, I forgot to let you know that it was ready months ago. Can you try merging?

**Comment by lrtitze** [comment]
Thanks, @an0 

I finally had enough time and energy to get back to this. I appreciate your patience.

**Pull request merged**
